services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: "${REGISTRY}/${PROJECT_PATH}/${IMAGE_NAME}:${IMAGE_TAG}"
    env_file: .env
    ports:
      - "${APP_PORT:-8000}:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
